// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Chefbook.Model;

namespace Chefbook.Model.Models
{
    public partial class Follow:IEntity
    {
        public Guid Id { get; set; }
        public Guid? FollowersId { get; set; }
        public Guid? FollowingId { get; set; }
        public DateTime? FollowDate { get; set; }

        public virtual User Followers { get; set; }
        public virtual User Following { get; set; }
    }
}