// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Chefbook.Model;

namespace Chefbook.Model.Models
{
    public partial class Image : IEntity
    {
        public Guid Id { get; set; }
        public Guid? PostId { get; set; }
        public string ImageUrls { get; set; }
        public string PublicId { get; set; }
    }
}