// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Chefbook.Model;

namespace Chefbook.Model.Models
{
    public partial class Notification : IEntity
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public Guid? TriggerUserId { get; set; }
        public Guid? TargetId { get; set; }
        public bool? TargetType { get; set; }
        public string NotificationDescription { get; set; }
        public DateTime? NotificationDate { get; set; }
        public string ImageUrl { get; set; }
    }
}