// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Chefbook.Model;

namespace Chefbook.Model.Models
{
    public partial class Sticker : IEntity
    {
        public Guid Id { get; set; }
        public Guid? PostId { get; set; }
        public string Name { get; set; }
        public long? SharingCount { get; set; }

        public virtual Post Post { get; set; }
    }
}