// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Chefbook.Model;

namespace Chefbook.Model.Models
{
    public partial class User : IEntity
    {
        public User()
        {
            Comment = new HashSet<Comment>();
            FollowFollowers = new HashSet<Follow>();
            FollowFollowing = new HashSet<Follow>();
            Like = new HashSet<Like>();
            Post = new HashSet<Post>();
        }

        public Guid Id { get; set; }
        public string NameSurName { get; set; }
        public bool? Gender { get; set; }
        public DateTime? Birthday { get; set; }
        public string Mail { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public DateTime? RegisterDate { get; set; }
        public string UserName { get; set; }
        public string ProfileImage { get; set; }
        public string CoverImage { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Follow> FollowFollowers { get; set; }
        public virtual ICollection<Follow> FollowFollowing { get; set; }
        public virtual ICollection<Like> Like { get; set; }
        public virtual ICollection<Post> Post { get; set; }
    }
}